### ISSUE TITLE
Is this tutorial up to date?

### ISSUE THREAD

**Issue by waynelapierre** [jonathancornelissen/highfrequency#55]
I am trying to find some online tutorials of the highfrequency package. 
Is this tutorial up to date?
http://highfrequency.herokuapp.com/

**Comment by kboudt** [comment]
No, it's outdated. We are working on a new tutorial. Will be ready by end of December.

**Comment by MislavSag** [comment]
Do you have development version of the new tutorial? In general, i am developing algo strategies in last few months. I started in python, mostly because of backtesting frameworks like backtrader and quantconnect and finance libraries like mlfiblab. But I like to do research part in R. 

In nutshell I would like to make contributions to this package, excpecialy if it is connected to algo trading. If I can help with something, please send me PM. 

I can maybe write some useful functions from mlfinlab like dollar bars or cusum filtering. Of labeling methods for financial ML.

**Comment by kboudt** [comment]
The new vignette is available at https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3917548
