### ISSUE TITLE
AJjumpTest and BNSjumpTest market open and close time

### ISSUE THREAD

**Issue by waynelapierre** [jonathancornelissen/highfrequency#69]
The package manual does not show marketOpen and marketClose arguments for the AJjumpTest and BNSjumpTest functions. How can I change the market open and close times for these two jump test functions?

**Comment by emilsjoerup** [comment]
They are typically only there when dealing with spot estimators and the like, and in some cases due to internal usage of functions that require the arguments set to function properly. You are more than welcome to implement any change you wish and make a pull request, then we can discuss the implementation details further.

**Comment by onnokleen** [comment]
@waynelapierre I agree with Emil. If you have more feature requests, it would be most beneficial for all users if you make a pull request. At the end it's an open source project and we provide support in our spare time.

**Comment by kboudt** [comment]
Thanks for the various comments @waynelapierre . It's good to have the user feedback.
